version: '3.8'

services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: converter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Message Queue
  redis:
    image: redis:7-alpine

  # 3. The Web API
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
      - shared_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/converter_db
      CELERY_BROKER_URL: redis://redis:6379/0

  # 4. The Background Worker
  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./app:/app/app
      - shared_data:/data
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/converter_db
      CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  postgres_data:
  shared_data: